In [2]:
#import packages
import tensorflow as tf

#### Rank of Tensors

In [6]:
rank1_tensor = tf.Variable(['Test', 'ok', 'Tim'])
rank2_tensor = tf.Variable([['Test', 'ok', 'yes'], ['what', 'you', 'yes']])
tf.rank(rank2_tensor) # numpy = 2 means the rank is 2 (deepest nested level)


<tf.Tensor: shape=(), dtype=int32, numpy=2>

#### Shape of Tensors

In [7]:
rank2_tensor.shape #number of inner list & number of element in each dimension

TensorShape([2, 3])

#### Reshape

In [9]:
tensor1 = tf.ones([1, 2, 3])
tensor2 = tf.reshape(tensor1, [2, 3, 1])
tensor3 = tf.reshape(tensor2, [3, -1])

# print out
print(tensor1) # 1 inner list, 2 list inside that, and 3 elements in each list
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [10]:
tf.zeros([3, 3, 3, 3])

<tf.Tensor: shape=(3, 3, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>